### PR TITLE
Fix accept-content deflate wrongfully using the DeflateEncoder

### LINKED ISSUE #118: Wrongfully uses deflate-raw for HTTP deflate encoding
Currently, mendes uses raw deflate (`async_compression::DeflateEncoder`) when the deflate accept encoding is chosen.

The HTTP spec is a bit ambiguous here, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding#deflate.
An accept encoding of deflate is not a raw deflate body (note that older Apache and IIS servers did this and thus some software has fallbacks during decoding) but a zlib container.

Tower (and thus axum) correctly maps `Accept-Encoding: deflate` to the async_compression::ZlibEncoder https://docs.rs/tower-http/latest/src/tower_http/compression/body.rs.html#31-42

I can submit a PR on Monday.

### PR DESCRIPTION
**Pull request by valkum**
Closes #118 
This adds the fix by switching to async_compression's `ZlibEncoder`. A test is included.
I also kept the deflate feature flag, so this should be backwards compatible. The used encoders are not public, thus this shouldn't be a breaking change. The `deflate` feature flag can be removed in a future version.

Furthermore, the feature flags for the different compression algorithms caused some issues when only a subset was enabled.
Fixing this caused some more code duplication. But the same as you, I can't think of an easy solution without huge rewrites.

### CODE REVIEW

File: mendes/src/body.rs [hunk 1]
```diff
@@ -8,23 +8,23 @@ use std::{io, mem, str};
...
 use async_compression::tokio::bufread::BrotliEncoder;
-#[cfg(feature = "deflate")]
-use async_compression::tokio::bufread::DeflateEncoder;
 #[cfg(feature = "gzip")]
 use async_compression::tokio::bufread::GzipEncoder;
+#[cfg(feature = "zlib")]
+use async_compression::tokio::bufread::ZlibEncoder;
 use bytes::{Buf, Bytes, BytesMut};
-#[cfg(any(feature = "brotli", feature = "deflate", feature = "gzip"))]
+#[cfg(any(feature = "brotli", feature = "zlib", feature = "gzip"))]
```
Comment (djc) [inline mendes/src/body.rs:16]: Mind changing the order to make them alphabetic again?

File: mendes/tests/body.rs [hunk 2]
```diff
@@ -1,31 +1,66 @@
...
+#![cfg(all(feature = "application", feature = "hyper", feature = "body-util"))]
 
 use std::sync::Arc;
 
+#[cfg(all(feature = "compression", feature = "zlib"))]
+use async_compression::tokio::write::ZlibDecoder;
+use http_body_util::BodyExt;
+#[cfg(all(feature = "compression", feature = "zlib"))]
+use tokio::io::AsyncWriteExt;
+
```
Comment (djc) [inline mendes/tests/body.rs:10]: Nit: no empty line before the `async_trait` import, please.

File: mendes/tests/body.rs [hunk 3]
```diff
@@ -34,26 +69,38 @@ struct App {}
 #[async_trait]
 impl Application for App {
     type RequestBody = Body;
-    type ResponseBody = String;
+    type ResponseBody = Body;
```
Comment (djc) [inline mendes/tests/body.rs:72]: Would like to have this as a separate commit so the diffs get a bit cleaner.

File: mendes/src/body.rs [hunk 4]
```diff
@@ -303,8 +303,8 @@ pub trait EncodeResponse {
 enum InnerBody {
     #[cfg(feature = "brotli")]
     Brotli(#[pin] BrotliEncoder<BufReader>),
-    #[cfg(feature = "deflate")]
-    Deflate(#[pin] DeflateEncoder<BufReader>),
+    #[cfg(feature = "zlib")]
+    Zlib(#[pin] ZlibEncoder<BufReader>),
```
Comment (djc) [inline mendes/src/body.rs:313]: Given that a lot of the diff here is just renaming the feature/enum variant/etc, suggest that you split this into two commits: first, one making the actual code change, second, renaming all the things.

**Comment by djc** [comment]
Oops! I guess we should have done more testing. How did this manifest itself?

**Comment by valkum** [comment]
> Oops! I guess we should have done more testing. How did this manifest itself?

As it seems, node only added support for the raw deflate fallback with node 22. node 21 complained with a zlib error when requesting from the hyper v1 mendes version.
AFAIK node 21 always sets accept-encoding to `gzip,deflate`. Previously, mendes returned a gzip encoded response in this case. (Not sure about the order) 
The new version returned nothing or the deflate one (depending on whether we manually call `encoded()` on the response) which causes the zlib error in node.

I think there are some more bugs, that probably need additions in application code (a server should return 406 if it cannot respond with the desired encoding).

**Comment by djc** [comment]
> I think there are some more bugs, that probably need additions in application code (a server should return 406 if it cannot respond with the desired encoding).

Aren't content encodings always optional? The server isn't required to use a content encoding, right?

File: mendes/src/body.rs (hunk 4 above)
Comment (valkum) [reply mendes/src/body.rs:313]: Split this commit into: test refactor, test addition, and rename (changing the implementation). Hope that is what you had in mind.

**Comment by valkum** [comment]
> > I think there are some more bugs, that probably need additions in application code (a server should return 406 if it cannot respond with the desired encoding).
> 
> Aren't content encodings always optional? The server isn't required to use a content encoding, right?

You are right. I had interpreted https://httpwg.org/specs/rfc9110.html#field.accept-encoding wrong. `identity` is implicit q:1.0.
Let me check the wireshark trace again. Might be another bug in node.

**Comment by valkum** [comment]
Did some more tests. Sort by key uses a tuple which means the order of the Encodings enum makes a difference when `Accept-Encoding: gzip,deflate`.
Due to the change to the enum the outcome now is `deflate`.

**Comment by djc** [comment]
> Did some more tests. Sort by key uses a tuple which means the order of the Encodings enum makes a difference when `Accept-Encoding: gzip,deflate`.
> Due to the change to the enum the outcome now is `deflate` (see https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0c016ca4dd5ea7651ea39d0a7be530d8).

Why do we need to include the `Encoding` in the sorting key?

File: mendes/Cargo.toml [hunk 5]
```diff
@@ -19,7 +19,7 @@ brotli = ["compression", "async-compression?/brotli"]
 chrono = ["dep:chrono"]
 compression = ["dep:async-compression", "dep:tokio", "dep:tokio-util"]
 cookies = ["http", "key", "dep:chrono", "dep:data-encoding", "dep:mendes-macros", "dep:postcard", "serde?/derive"]
-deflate = ["compression", "async-compression?/deflate"]
+deflate = ["compression", "async-compression?/deflate", "async-compression?/zlib"]
```
Comment (djc) [inline mendes/Cargo.toml]: Presumably this shouldn't be part of the initial testing commit? (Also this change gets reverted in the next commit.)

File: mendes/tests/body.rs [hunk 6]
```diff
@@ -18,17 +24,39 @@ async fn test_json_decode() {
     let body = rsp.into_body().collect().await.unwrap().to_bytes();
     assert_eq!(String::from_utf8_lossy(&body), "6");
 }
+
+#[cfg(all(feature = "compression", feature = "deflate"))]
+#[tokio::test]
+async fn test_deflate_compression() {
+    use std::assert_eq;
```
Comment (djc) [inline mendes/tests/body.rs:31]: Pretty sure `assert_eq!()` is in the prelude.

File: mendes/tests/body.rs [hunk 7]
```diff
@@ -18,17 +24,39 @@ async fn test_json_decode() {
...
-fn path_request(path: &str, body: &str) -> Request<Body> {
-    Request::builder()
+fn path_request(path: &str, body: &str, compression: Option<&'static str>) -> Request<Body> {
+    let mut request = Request::builder()
         .method(Method::POST)
         .uri(format!("https://example.com{path}"))
-        .header("Content-Type", "application/json; charset=utf-8")
-        .body(body.to_owned().into())
-        .unwrap()
+        .header("Content-Type", "application/json; charset=utf-8");
```
Comment (djc) [inline mendes/tests/body.rs:55]: Use constants for the header keys?

File: mendes/src/body.rs (hunk 4 above)
Comment (djc) [reply mendes/src/body.rs:313]: It's not what I was describing in my previous comment: the idea is that all of the `deflate` -> `zlib` renaming (for both the Cargo feature and the enum variant) should be in a separate commit from the (much smaller) change to actually use `ZlibEncoder` for the `deflate` encoding.

File: mendes/Cargo.toml (hunk 5 above)
Comment (valkum) [reply mendes/Cargo.toml]: It needs to be, because we use the ZlibEncoder in the test and it is not enabled by default. I rather have the test that shows it is broken in the history before the fix.

**Comment by valkum** [comment]
> > Did some more tests. Sort by key uses a tuple which means the order of the Encodings enum makes a difference when `Accept-Encoding: gzip,deflate`.
> > Due to the change to the enum the outcome now is `deflate` (see https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0c016ca4dd5ea7651ea39d0a7be530d8).
> 
> Why do we need to include the `Encoding` in the sorting key?

We probably don't need to, it's just how it was and currently is implemented.

File: mendes/src/body.rs (hunk 4 above)
Comment (valkum) [reply mendes/src/body.rs]: split these two steps as well.

File: mendes/Cargo.toml (hunk 5 above)
Comment (djc) [reply mendes/Cargo.toml]: Right, that makes sense.

**Review by djc — APPROVED** [review]
